name: Run process_repos.py

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch: 

jobs:
  process_repos:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process repos
        run: python process_repos.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Process repos'
          pull: '--rebase --autostash'
