name: Update README

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'   # Include all markdown files
    paths-ignore:
      - 'README.md' # Exclude README.md specifically


permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate README.md
        run: |
          python generate_readme.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-readme
          commit-message: "Update README.md"
          title: "Update README.md"
          body: "Update README.md"
          add-paths: |
            README.md
